on:
  push:
    branches:
    - staging
name: "Deploy to test.wim.usgs.gov/fim"
jobs:
  pushToTest:
    name: Push to TEST
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15'
    - run: npm run-script build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: aws s3 cp /home/runner/work/fim-js/fim-js/build/ s3://test.wim.usgs.gov/fim/ --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@5faabb4216b20af98fe77b6d9048d24becfefd31
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":test: Successfully deployed *fim-js* to test.wim.usgs.gov/fim :fire:"

